language: node_js
before_install:
  - cd workout-finances-gui
  - ssh-keyscan -t $TRAVIS_SSH_KEY_TYPES -H $DEPLOY_HOST 2>&1 | tee -a $HOME/.ssh/known_hosts
node_js:
  - "7"

branches:
  only:
  - master
  - develop

script:
  - npm run build

after_success:
  - echo "${SSH_CODE}" | base64 --decode >/tmp/sftp_rsa
  - curl --ftp-create-dirs
      -T filename
      --key /tmp/sftp_rsa
      sftp://${DEPLOY_LOGIN}:${DEPLOY_PASSWORD}@$DEPLOY_HOST/home/deploy/workout-finances/gui/dist